network definition
devopsacademyau/2020-feb-project1-group1 pull request #13
Opened 2020-04-15 14:21 UTC by christina-roperto

Terraform didn't work on my pc because I couldn't use the default vpc. 

I think it's better to have it explicit. Let me know what you think :)

2020-04-16 08:57 UTC, lgothelipe commented
how about create the networking as a module?

2020-04-17 12:02 UTC, christina-roperto commented
## Network stack #23 
  - vpc (/16 cidr)
  - 4 subnets (/24 cidr) public/private in 2 different AZ'stack
  - 2 route table public/private
  - 2 nacl public/private (ALLOW ALL is not permitted)
  - internet gateway

done:
- [x] I can run a instance on public subnet and another one on private subnet
-- I manually created them for testing on my server
- [x] I can access the public one using ssh from my local machine through internet
-- yes, I did
- [x] I can't directly access the private instance from internet
-- it's not possible as it doesn't even have a public IP address
- [x] I can ssh the private instance from the public one
-- yup
- [x] no security groups or nacls have `ALLOW ALL`
-- there's no "ALLOW ALL"

As discussed with @denstorti this should fulfill all the criteria for this issue.

2020-04-17 15:46 UTC, lgothelipe requested changes
change on nacls ingress

2020-04-17 15:46 UTC, lgothelipe commented on terraform/modules/networking/main.tf
> +  # SSH
As we going to use a web application on a docker container, we will use ports 80 and 443 instead

2020-04-18 06:22 UTC, christina-roperto commented on terraform/modules/networking/main.tf
> +  # SSH
I think we should not prevent the pull request to go ahead because of features are not required yet.

The pull request that adds the web should open that rule because only then we can test if it is working.

In any case, I am fixing the AWS Service as requested in #26

2020-04-18 07:22 UTC, luizfdsilva approved these changes
lgtm

2020-04-18 07:27 UTC, merged