applying terraform fmt and code cleanup
devopsacademyau/2020-feb-project1-group1 pull request #26
Opened 2020-04-17 12:44 UTC by christina-roperto

2020-04-17 14:47 UTC, lgothelipe requested changes
please change the subnets variable

2020-04-17 14:47 UTC, lgothelipe commented on terraform/modules/aws-ecs-service/main.tf
> +    subnets          = var.subnets_id
Please add the subnets_id variable (type list) to variables.tf under modules/aws-ecs-service and add it on the main.tf under the ecs-service module.

2020-04-18 06:13 UTC, christina-roperto commented on terraform/modules/aws-ecs-service/main.tf
> +    subnets          = var.subnets_id
Because this is a module, we need to declare the variable then pass it in the main, not just changing this line.

We should not have merged it to master (my bad) as the code was not working before. I was thinking of pushing the fix as a separate pull request because this one is the networking. I  ignored that module locally in the hope you would change it, when I change we may introduce conflicts when you make your changes.

2020-04-18 06:16 UTC, christina-roperto commented on terraform/modules/aws-ecs-service/main.tf
> +    subnets          = var.subnets_id
This is only applying terraform and code cleanup, no functional changes.

2020-04-18 06:16 UTC, christina-roperto commented
This is has no functional changes, just code style and removing comments.

2020-04-18 07:25 UTC, luizfdsilva submitted a review, later dismissed
lgtm

2020-04-18 07:36 UTC, luizfdsilva approved these changes
lgtm

2020-04-18 07:37 UTC, luizfdsilva approved these changes

2020-04-18 07:39 UTC, luizfdsilva approved these changes

2020-04-18 08:29 UTC, lgothelipe approved these changes
lgtm

2020-04-18 08:30 UTC, merged