Added AWS RDS module
devopsacademyau/2020-feb-project1-group1 pull request #29
Opened 2020-04-18 07:11 UTC by LuizFDS

# AWS RDS Module

2020-04-18 07:48 UTC, christina-roperto requested changes
wow Luiz, this is very comprehensive. I think you did more than expected and I don't even know most of it! I can't approve it yet though as I can't run it on my PC (otherwise my network will be destroyed). Happy to review it once the #23 network stack is reviewed and merged because you'll need the resources from it. Also, I put a group name variable which you can reuse for your files :)

2020-04-18 07:48 UTC, christina-roperto commented on terraform/main.tf
> +# resource "aws_db_instance" "mysql-wordpress" {
@denstorti mentioned that we don't need to commit commented out code.

2020-04-18 07:48 UTC, christina-roperto commented on terraform/main.tf
> +# Data sources to get VPC, subnets and security group details
After merging #23 this needs to change to the VPC generated by the networking.

2020-04-18 07:48 UTC, christina-roperto commented on terraform/main.tf
> +  multi_az          = false
is it going to have high availability? I think this is good for now and we can worry about HA once everything is working :)

2020-04-19 07:48 UTC, christina-roperto reviewed
I will have a look as soon as I can.

2020-04-19 08:45 UTC, christina-roperto reviewed
lgtm, there are minor things like formatting but that could be done later as it's more important to get this merge. However I can't test in my local because the network module is missing.

2020-04-19 08:45 UTC, christina-roperto commented on terraform/main.tf
> +  task_arn   = module.aws-ecs-task-def.arn
needs `terraform fmt`

2020-04-19 08:45 UTC, christina-roperto commented on terraform/main.tf
> +module "networking" {
Why is it adding networking? This should be done already.

2020-04-19 08:45 UTC, christina-roperto commented on terraform/modules/aws-rds/.gitignore
> +test/*
What is it for? I'll ask you on slack later...

2020-04-19 08:45 UTC, christina-roperto commented on terraform/modules/aws-rds/main.tf
> +  database_name             = "${var.database_name}"
Terraform 0.12 suggests using `var.database_name` instead of `"${var.database_name}"` as that format is deprecated: Warning: Interpolation-only expressions are deprecated

2020-04-19 08:45 UTC, christina-roperto commented on terraform/modules/aws-rds/output.tf
> +// aws_rds_cluster
nice adding descriptions, i should start doing those in mine too

2020-04-19 08:45 UTC, christina-roperto commented on terraform/modules/aws-rds/variables.tf
> +variable "security_group_ids" {
The security groups I think should be created in the module, as they refer to the RDS itself

2020-04-19 08:45 UTC, christina-roperto commented on terraform/variables.tf
> -variable "username" {
good idea renaming to `db_username`, makes more sense

2020-04-19 08:45 UTC, christina-roperto commented on terraform/variables.tf
> +variable "cidr_vpc" {
why are you adding this? I already added before ...

2020-04-19 09:08 UTC, lgothelipe commented on terraform/variables.tf
> -variable "username" {
this has been done already

2020-04-19 09:12 UTC, christina-roperto approved these changes

2020-04-19 10:21 UTC, closed without merging